### ISSUE TITLE
Error while trying to create/update issue with tags

### ISSUE THREAD

**Issue by resetko** [ixti/redmine_tags#113]
```
Started PATCH "/issues/566" for 127.0.0.1 at 2015-12-08 13:52:59 +0300
Processing by IssuesController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"jlD2/oym4IQDBlMRalGhSJHjlj28qjYc1TOTxfY2LP56D8rG+Cy6dRkdY1tL8hrEziOHWZ20uYwrerbxFGA5vQ==", "issue"=>{"tracker_id"=>"5", "subject"=>"Верстка СТРАНИЦЫ      урока", "description"=>"", "status_id"=>"1", "priority_id"=>"2", "assigned_to_id"=>"9", "category_id"=>"4", "fixed_version_id"=>"4", "parent_issue_id"=>"", "start_date"=>"2015-12-08", "due_date"=>"", "estimated_hours"=>"", "tag_list"=>"страница", "notes"=>"", "private_notes"=>"0", "lock_version"=>"1"}, "was_default_status"=>"1", "time_entry"=>{"hours"=>"", "activity_id"=>"", "comments"=>""}, "last_journal_id"=>"1111", "commit"=>"Принять", "id"=>"566"}
  Current user: resetko (id=9)
Mysql2::Error: Unknown column 'taggings_count' in 'field list': UPDATE `tags` SET `taggings_count` = COALESCE(`taggings_count`, 0) + 1 WHERE `tags`.`id` = 1
Completed 500 Internal Server Error in 37ms (ActiveRecord: 5.1ms)

ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'taggings_count' in 'field list': UPDATE `tags` SET `taggings_count` = COALESCE(`taggings_count`, 0) + 1 WHERE `tags`.`id` = 1):
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:162:in `call_hook'
  app/controllers/issues_controller.rb:481:in `block in save_issue_with_child_records'
  app/controllers/issues_controller.rb:470:in `save_issue_with_child_records'
  app/controllers/issues_controller.rb:180:in `update'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

I've encountered this error immediately after install. Just tried to add tags to already existing issue.

```
bundle install
RAILS_ENV=production rake redmine:plugins:migrate
```
was executed without errors.

**Comment by sdwolf** [comment]
See the ["To make it actually work"](https://github.com/ixti/redmine_tags#to-make-it-actually-work) section from the README.

**Comment by PowerKiKi** [comment]
@resetko you may want to have a look at https://github.com/kamilkp/angular-vs-repeat

**Comment by PowerKiKi** [comment]
mmhh.. .my last comment had really nothing to do with this thread... 

Anyway this issue is solved on master, see README
