### ISSUE TITLE
Internal Server Error - 500

### ISSUE THREAD

**Issue by adrianobr** [ixti/redmine_tags#125]
Environment:
   Redmine version 3.2.0.stable
   Ruby version 2.1.7-P400 (08/18/2015) [x86_64-linux-gnu]
   Rails version 4.2.5
   Environment production
   PostgreSQL database adapter

Again tested your plugin:
By clicking on Plugins> Configure> Redmine Tags

Is the error below:
Internal error 500

![tags](https://cloud.githubusercontent.com/assets/7975205/12294556/90c0ecd4-b9e2-11e5-839e-7b0d1a451027.PNG)

**Comment by marius-balteanu** [comment]
Hi,

Can you paste here the logs with the error? (in a classic setup the logs are located in document_root/logs/production.log)

Thanks,
Marius

**Comment by lacek** [comment]
I have the similar issue, below are the logs from production.log:

```
Started GET "/issues/imports/new" for 127.0.0.1 at 2016-02-04 14:20:52 +0000
Processing by ImportsController#new as HTML
  Current user: xxx (id=1)
  Rendered plugins/redmine_agile/app/views/agile_boards/_issues_sidebar.html.erb (0.3ms)
  Rendered plugins/redmine_agile/app/views/agile_charts/_agile_charts.html.erb (0.3ms)
  Rendered plugins/redmine_tags/app/views/issues/_tags_sidebar.html.erb (26.5ms)
  Rendered issues/_sidebar.html.erb (29.1ms)
  Rendered imports/new.html.erb within layouts/base (31.8ms)
Completed 500 Internal Server Error in 44ms (ActiveRecord: 1.2ms)

ActionView::Template::Error (undefined local variable or method `sidebar_tags' for #<#<Class:0x000000053f6830>:0x00
0000053c9128>):
    1: <% if !sidebar_tags.empty? && !@issue %>
    2:   <%= stylesheet_link_tag 'jquery.tagit.css', plugin: 'redmine_tags' %>
    3:   <%= stylesheet_link_tag 'redmine_tags', plugin: 'redmine_tags' %>
    4:   <h3><%= l :tags %></h3>
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/issues/_sidebar.html.erb:22:in `_app_views_issues__sidebar_html_erb___348753206144761399_73832740'
  app/views/imports/new.html.erb:14:in `block in _app_views_imports_new_html_erb___2642196432794062764_43830880'
  app/views/imports/new.html.erb:13:in `_app_views_imports_new_html_erb___2642196432794062764_43830880'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

and system info:

```
Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.8-p440 (2015-12-16) [x86_64-linux-gnu]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Darcs                          2.8.4
  Mercurial                      2.8.2
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            2.7.0
  Filesystem                     
Redmine plugins:
  easy_gantt                     2016.01.1000
  quick_edit                     0.0.9
  redmine_agile                  1.3.13
  redmine_checklists             3.1.3
  redmine_code_review            0.7.0
  redmine_custom_css             0.1.6
  redmine_github_hook            2.2.0
  redmine_tags                   3.1.0
  redmine_theme_changer          0.2.0
```

**Comment by sdwolf** [comment]
@lacek I will take a look at it.
@adrianobr Your problem may be unrelated, please paste the error stack trace from the logs.

**Comment by sdwolf** [comment]
@lacek you can find a fix for this on master

**Comment by lacek** [comment]
Great! Found the fix at 964e7c7.

**Comment by sdwolf** [comment]
@adrianobr I've commited 60bc28187cf708f074ff31b6031b63e6c379778e with a potential fix to your problem.

**Comment by adrianobr** [comment]
YES!! Problem Solved!
