### ISSUE TITLE
Breaks plugin "Favorite projects"

### ISSUE THREAD

**Issue by AThomsen** [ixti/redmine_tags#132]
Installing *redmine_tags* breaks the [Favorite Projects plugin](http://www.redminecrm.com/projects/favoriteprojects/pages/1)

Redmine 3.2
MS SQLServer
[Latest redmine_tags](https://github.com/ixti/redmine_tags/commit/32a9aeb7c110b67c3386dd21c61b89e11853ac9d)

```
Started GET "/rm/favorite_projects/search" for 127.0.0.1 at 2016-03-08 20:31:59 +0100
Processing by FavoriteProjectsController#search as HTML
Completed 500 Internal Server Error in 181ms (ActiveRecord: 80.0ms)

ActiveRecord::StatementInvalid (TinyTds::Error: Column 'tags.taggings_count' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.: EXEC sp_executesql N'SELECT  tags.*, COUNT(DISTINCT taggings.taggable_id) AS count FROM [tags] JOIN taggings ON taggings.tag_id = tags.id  JOIN projects ON projects.id = taggings.taggable_id 
            AND taggings.taggable_type = N''Project'' GROUP BY tags.id, tags.name  HAVING COUNT(*) > 0  ORDER BY tags.name OFFSET 0 ROWS FETCH NEXT 30 ROWS ONLY'):
  plugins/redmine_favorite_projects/app/models/favorite_projects_query.rb:141:in `initialize_available_filters'
  app/models/query.rb:366:in `available_filters'
  app/models/query.rb:408:in `type_for'
  app/models/query.rb:265:in `block in validate_query_filters'
  app/models/query.rb:263:in `each_key'
  app/models/query.rb:263:in `validate_query_filters'
  plugins/redmine_favorite_projects/app/controllers/favorite_projects_controller.rb:14:in `search'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

**Comment by sdwolf** [comment]
I will take a look at it when I have some time (probably this weekend).

**Comment by AThomsen** [comment]
Actually, I think it's due to a bug in the redmine_crm gem. I've submitted the a patch to the authors and will keep this post updated with the status.


[redmine_crm.patch.txt](https://github.com/ixti/redmine_tags/files/165768/redmine_crm.patch.txt)

**Comment by sdwolf** [comment]
Did you receive any feedback on the submitted patch?

**Comment by sdwolf** [comment]
Closing this since it may have been fixed in the other plugin, if the problem persists feel free to open again.
