### ISSUE TITLE
unfinish the copying process (ActiveRecord::StaleObjectError (Attempted to update a stale object: Issue):)

### ISSUE THREAD

**Issue by ghost** [ixti/redmine_tags#143]
When I try to copy the ticket having some child tickets, a browser can't show a ticket after copying.
Redmine recorded the error:

```
ActiveRecord::StaleObjectError (Attempted to update a stale object: Issue):
  app/models/issue.rb:182:in `create_or_update'
  plugins/redmine_tags/lib/redmine_tags/hooks/model_issue_hook.rb:18:in `controller_issues_new_after_save'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:91:in `call_hook'
  app/controllers/issues_controller.rb:142:in `create'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

I checked Redmine 2.6.10 and 3.2.1. Both version's redmine recorded the same error.
I removed this plugin, the copying process work correctly. 
What is this plugin having a problem?

Thanks.

**Comment by sdwolf** [comment]
I am unable to reproduce this, tried with 3.2.1 and 3.3.0 and both worked as expected. I believe this may be an incompatibility with another plugin you have. 

Can you please make sure you have the latest version of redmine_tags (master branch) and remove each of the other plugins you have, one by one, until the problem disappears, so you can pinpoint which one exactly has the conflict. If you can reproduce it with just those two then I may be able to as well so I can assist you.

**Comment by jcormier** [comment]
Ran into this problem as well.  This problem seemed to crop up when copying issues that had subtasks.  Though not every task with subtasks fails.  Played with the issues in question for over an hour to determine if there was a certain setting that triggered this bug and couldn't find one.

Removing the redmine_tags plugin immediately caused the problem to go away.  If there is some debugging steps I can do please let me know.

```
Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.1.9-p490 (2016-03-30) [x86_64-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Darcs                          2.8.4
  Mercurial                      2.8.2
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            2.10.1
  Filesystem                     
Redmine plugins:
  google_analytics_plugin        1.0.0
  redmine_banner                 0.1.2
  redmine_charts2                0.2.1
  redmine_checklists             3.1.5
  redmine_favourite_projects     0.7
  redmine_jstoolbar_ext          0.2.1
  redmine_jstoolbar_ext_buttons  0.2.1
  redmine_jstoolbar_ext_images   0.3.1
  redmine_project_alias_2        1.0.2
  redmine_release_notes          1.3.1
  redmine_silencer               0.4.1
  redmine_wiki_extensions        0.7.0
  redmine_wiki_notes             0.0.2
  redmine_xlsx_format_issue_exporter 0.1.3
```

```
Started POST "/redmine/projects/wo/issues" for 127.0.0.1 at 2017-01-18 12:04:06 -0500
Processing by IssuesController#create as HTML
  Parameters: {"utf8"=>"✓", ...}  Current user: jcormier (id=360)
  Rendered mailer/_issue.text.erb (7.8ms)
  Rendered mailer/issue_add.text.erb within layouts/mailer (16.1ms)
  Rendered mailer/_issue.html.erb (8.0ms)
  Rendered mailer/issue_add.html.erb within layouts/mailer (15.3ms)
  Rendered mailer/_issue.text.erb (3.1ms)
  Rendered mailer/issue_add.text.erb within layouts/mailer (4.4ms)
  Rendered mailer/_issue.html.erb (6.5ms)
  Rendered mailer/issue_add.html.erb within layouts/mailer (7.5ms)
  Rendered mailer/_issue.text.erb (2.7ms)
  Rendered mailer/issue_add.text.erb within layouts/mailer (3.4ms)
  Rendered mailer/_issue.html.erb (8.9ms)
  Rendered mailer/issue_add.html.erb within layouts/mailer (9.5ms)
  Rendered mailer/_issue.text.erb (2.4ms)
  Rendered mailer/issue_add.text.erb within layouts/mailer (3.1ms)
  Rendered mailer/_issue.html.erb (8.0ms)
  Rendered mailer/issue_add.html.erb within layouts/mailer (8.7ms)
Completed 409 Conflict in 2951ms (ActiveRecord: 1004.9ms)

ActiveRecord::StaleObjectError (Attempted to update a stale object: Issue):
  app/models/issue.rb:210:in `create_or_update'
  plugins/redmine_tags/lib/redmine_tags/hooks/model_issue_hook.rb:18:in `controller_issues_new_after_save
'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:91:in `call_hook'
  app/controllers/issues_controller.rb:141:in `create'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by marius-balteanu** [comment]
I can reproduce using 3.2.0 version of the plugin. Can you test, please, with the new version?

**Comment by xuliaP** [comment]
redmine 3.3.4 - also error

**Comment by PowerKiKi** [comment]
This project only support Redmine 4. You should try upgrading.

**Comment by xuliaP** [comment]
i think this error played back in redmine 4 too

**Comment by xuliaP** [comment]
im wrong ...all ok in 4

**Comment by themilkman** [comment]
JFTR: I got exactly this issue with Redmica 2.0, not by 1.3. Also another plugin hook using `controller_issues_new_after_save` provoked this so there might be smth. coming up again.
