### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by JL2014** [ixti/redmine_tags#144]
Hi,

When I want to use your plugin on last version of redmine (3.3.0.devel.15732), I have an internal error, logs says :

```
Completed 500 Internal Server Error in 2250ms (ActiveRecord: 48.4ms)

ActionView::Template::Error (undefined method `to_sym' for nil:NilClass):
    1: <% if defined?(sidebar_tags) && !sidebar_tags.empty? && !@issue %>
    2:   <%= stylesheet_link_tag 'jquery.tagit.css', plugin: 'redmine_tags' %>
    3:   <%= stylesheet_link_tag 'redmine_tags', plugin: 'redmine_tags' %>
    4:   <h3><%= l :tags %></h3>
  plugins/redmine_tags/app/helpers/issues_tags_helper.rb:5:in `sidebar_tags'
  plugins/redmine_tags/app/views/issues/_tags_sidebar.html.erb:1:in `_65dff3f918480828a27ed84b638c01b2'
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/issues/_sidebar.html.erb:22:in `_200f2a808b581361310413772489ebf7'
  app/views/issues/index.html.erb:57:in `block in _031d4ccdb1f50eaaa2d873fbc69e4ebc'
  app/views/issues/index.html.erb:56:in `_031d4ccdb1f50eaaa2d873fbc69e4ebc'
  app/controllers/issues_controller.rb:76:in `block (2 levels) in index'
  app/controllers/issues_controller.rb:75:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'
```

and sometimes:

```
Completed 500 Internal Server Error in 4288ms (ActiveRecord: 104.8ms)

ActionView::Template::Error (undefined method `[]' for false:FalseClass):
    1: <% if defined?(sidebar_tags) && !sidebar_tags.empty? && !@issue %>
    2:   <%= stylesheet_link_tag 'jquery.tagit.css', plugin: 'redmine_tags' %>
    3:   <%= stylesheet_link_tag 'redmine_tags', plugin: 'redmine_tags' %>
    4:   <h3><%= l :tags %></h3>
  plugins/redmine_tags/app/helpers/issues_tags_helper.rb:5:in `sidebar_tags'
  plugins/redmine_tags/app/views/issues/_tags_sidebar.html.erb:1:in `_871028c66b521ecd197f808f8157e337'
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/issues/_sidebar.html.erb:22:in `_3ca57e59f31dd02a5d2ad322eac4c097'
  plugins/event_notifications/app/views/issues/show.html.erb:148:in `block in _f8ab242f79668300520a28d04ae6977f'
  plugins/event_notifications/app/views/issues/show.html.erb:147:in `_f8ab242f79668300520a28d04ae6977f'
  app/controllers/issues_controller.rb:118:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:115:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'

```

**Comment by PowerKiKi** [comment]
I don't think you'll get much support for an unreleased version of Redmine. I'd suggest you revert back to stable Redmine 3.3.0. Or, actually better, would be to suggest a fix via a PR.
