### ISSUE TITLE
Compatibility 3.4.2.stable issue

### ISSUE THREAD

**Issue by keithkuk** [ixti/redmine_tags#176]
My Environment is
 
  Redmine version                3.4.2.stable
  Ruby version                   2.4.1-p111 (2017-03-22) [x86_64-linux]
  Rails version                  4.2.8

Are there any plans to update the themes to Redmine 3.4.2.stable ?

Thanks a lot for your work.

**Comment by westberliner** [comment]
Maybe I have the same issue. I created a fresh Redmine@3.4.2 with only redmine_tags as an additional plugin. In my logs I got this message while opening the issues overview:

```
Started` GET "/issues" for 79.247.115.49 at 2017-08-28 11:36:55 +0000
Processing by IssuesController#index as HTML
  Current user: admin (id=1)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_issues_index_header_tags.html.haml (13.1ms)
  Rendered plugins/redmine_issues_tree/app/views/issues_trees/_link_to_tree_view.html.haml (1.6ms)
  Rendered queries/_filters.html.erb (6.6ms)
  Rendered plugins/redmine_issues_tree/app/views/issues/index.html.erb within layouts/base (31.0ms)
Completed 500 Internal Server Error in 58ms (ActiveRecord: 9.9ms)

ActionView::Template::Error (undefined method `remote' for {:name=>"Tags", :type=>:list_optional, :order=>6, :values=>[]}:Hash):
    1: <%= javascript_tag do %>
    2: var operatorLabels = <%= raw_json Query.operators_labels %>;
    3: var operatorByType = <%= raw_json Query.operators_by_filter_type %>;
    4: var availableFilters = <%= raw_json query.available_filters_as_json %>;
    5: var labelDayPlural = <%= raw_json l(:label_day_plural) %>;
    6: 
    7: var filtersUrl = <%= raw_json queries_filter_path(:project_id => @query.project.try(:id), :type => @query.type) %>;
  app/models/query.rb:464:in `block in available_filters_as_json'
  app/models/query.rb:462:in `each'
  app/models/query.rb:462:in `available_filters_as_json'
  app/views/queries/_filters.html.erb:4:in `block in _app_views_queries__filters_html_erb___782144111790852937_39885780'
  app/views/queries/_filters.html.erb:1:in `_app_views_queries__filters_html_erb___782144111790852937_39885780'
  plugins/redmine_issues_tree/app/views/issues/index.html.erb:27:in `block in _plugins_redmine_issues_tree_app_views_issues_index_html_erb___2987645860686363611_32513960'
  plugins/redmine_issues_tree/app/views/issues/index.html.erb:19:in `_plugins_redmine_issues_tree_app_views_issues_index_html_erb___2987645860686363611_32513960'
  app/controllers/issues_controller.rb:51:in `block (2 levels) in index'
  app/controllers/issues_controller.rb:46:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```
Adding or viewing an issue works fine.

**Comment by westberliner** [comment]
Sry, I thought my git pull went through. But I was 65 commits behind. It works now.

**Comment by PowerKiKi** [comment]
Closing for lack of relevant information
