### ISSUE TITLE
rake aborted NameError: uninitialized constant ActiveSupport::Reloader

### ISSUE THREAD

**Issue by janekska** [ixti/redmine_tags#210]
```
Environment:
  Redmine version                3.3.3.stable
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.3
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  accept                         0.0.2
  additionals                    2.0.9
  event_notifications            3.2.1
  localizable                    0.4.0
  redmine_better_gantt_chart     0.9.0
  redmine_checklists             3.1.11
  redmine_contacts               4.2.2
  redmine_contacts_invoices      4.1.6
  redmine_custom_reports         0.1.5
  redmine_dashboard              2.7.1
  redmine_logs                   0.1.0
  redmine_mail_reminder          3.0.0.0001
  redmine_mentions               0.0.1
  redmine_theme_changer          0.2.0
  redmine_timelog_timer          2.0.1
  redmine_work_time              0.3.4
```

Getting problem when install:

```
au@myserv:/usr/local/redmine/plugins# rake redmine:plugins:migrate NAME=redmine_tags  RAILS_ENV=production
(in /usr/local/redmine)
rake aborted!
NameError: uninitialized constant ActiveSupport::Reloader
/usr/local/redmine/plugins/redmine_tags/init.rb:5:in `<top (required)>'
/var/lib/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/redmine/lib/redmine/plugin.rb:155:in `block in load'
/usr/local/redmine/lib/redmine/plugin.rb:146:in `each'
/usr/local/redmine/lib/redmine/plugin.rb:146:in `load'
/usr/local/redmine/config/initializers/30-redmine.rb:21:in `<top (required)>'
/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
/var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
/usr/local/redmine/config/environment.rb:14:in `<top (required)>'
/var/lib/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/var/lib/gems/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by marcodamm** [comment]
It looks like you tried to install the most recent version of redmine_tags, which is only compatible with redmine 4.0.0 and later.

Make sure you are using a redmine_tags release which is compatible with your redmine version (3.3.3)

Either checkout the release tag via git or download the 3.2.2 from the releases page here https://github.com/ixti/redmine_tags/releases
