### ISSUE TITLE
500 Internal error

### ISSUE THREAD

**Issue by AndreyKiryliuk** [ixti/redmine_tags#214]
### **Environment:**
   Redmine version 4.0.4
   Ruby version 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
   Rails version (5.2.3, 4.2.7.1)
   Environment production
   MySQL database adapter

### when i open  my page i see:

```
Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.
```

### in logs:
```
Started GET "/my/page" for 192.168.1.190 at 2019-06-25 17:26:34 +0000
Processing by MyController#page as HTML
  Current user: test (id=3)
  Rendering my/page.html.erb within layouts/base
  Rendered my/page.html.erb within layouts/base (30.7ms)
Completed 500 Internal Server Error in 38ms (ActiveRecord: 15.6ms)

ActionView::Template::Error (The single-table inheritance mechanism failed to locate the subclass: 'ContactCustomField'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite CustomField.inheritance_column to use another column for that information.):
    10: <div id="my-page">
    11: <% @groups.each do |group| %>
    12:   <div id="list-<%= group %>" class="block-receiver">
    13:     <%= render_blocks(@blocks[group], @user) %>
    14:   </div>
    15: <% end %>
    16: </div>

app/models/query.rb:1301:in `group_by'
app/models/query.rb:1301:in `add_associations_custom_fields_filters'
app/models/issue_query.rb:175:in `initialize_available_filters'
app/models/query.rb:615:in `available_filters'
plugins/redmine_tags/lib/redmine_tags/patches/issue_query_patch.rb:35:in `available_filters_with_tags'
app/models/query.rb:625:in `add_filter'
plugins/redmine_contacts/lib/redmine_contacts/patches/query_patch.rb:47:in `add_filter_with_contacts'
app/helpers/my_helper.rb:98:in `render_issuesassignedtome_block'
app/helpers/my_helper.rb:64:in `render_block_content'
app/helpers/my_helper.rb:35:in `render_block'
app/helpers/my_helper.rb:27:in `block in render_blocks'
app/helpers/my_helper.rb:26:in `each'
app/helpers/my_helper.rb:26:in `render_blocks'
app/views/my/page.html.erb:13:in `block in _app_views_my_page_html_erb___1593047502546273263_47005384228780'
app/views/my/page.html.erb:11:in `each'
app/views/my/page.html.erb:11:in `_app_views_my_page_html_erb___1593047502546273263_47005384228780'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by yzzy** [comment]
@AndreyKiryliuk 
It seems there is a problem with _Redmine CRM_ plugin. I see your contacts have custom fields, so it looks like you have a PRO version of this plugin, and I can't test it and try to reproduce this error.
1. Ensure that you're using latest version (4.2.5) of _Redmine CRM_ plugin.
2. Can you uninstall _redmine_tags_ plugin and check if this error disappears?
