### ISSUE TITLE
Completed 500 Internal Server Error on Redmine 4.1.1

### ISSUE THREAD

**Issue by Cycloone** [ixti/redmine_tags#221]
Hello, i`m get error after migrate to Redmine 4.1.1 with latest version of redmine_tags:

> redmine_1  | I, [2020-09-11T15:04:55.656523 #1]  INFO -- : Completed 500 Internal Server Error in 3481ms (ActiveRecord: 3318.8ms)
redmine_1  | F, [2020-09-11T15:04:55.657246 #1] FATAL -- :
redmine_1  | F, [2020-09-11T15:04:55.657266 #1] FATAL -- : ActionView::Template::Error (undefined method `with_indifferent_access' for #<ActionController::Parameters:0x00007febe9c04540>):
redmine_1  | F, [2020-09-11T15:04:55.657333 #1] FATAL -- :     1: <% if defined?(sidebar_tags) && !sidebar_tags.empty? && !@issue %>
redmine_1  |     2:   <%= stylesheet_link_tag 'jquery.tagit.css', plugin: 'redmine_tags' %>
redmine_1  |     3:   <%= stylesheet_link_tag 'redmine_tags', plugin: 'redmine_tags' %>
redmine_1  |     4:   <h3><%= l :tags %></h3>
redmine_1  | F, [2020-09-11T15:04:55.657348 #1] FATAL -- :
redmine_1  | F, [2020-09-11T15:04:55.657365 #1] FATAL -- : plugins/redmine_tags/lib/redmine_tags.rb:3:in `new'
redmine_1  | plugins/redmine_tags/lib/redmine_tags.rb:3:in `settings'
redmine_1  | plugins/redmine_tags/app/helpers/issues_tags_helper.rb:5:in `sidebar_tags'
redmine_1  | plugins/redmine_tags/app/views/issues/_tags_sidebar.html.erb:1:in `_plugins_redmine_tags_app_views_issues__tags_sidebar_html_erb___2021962398656968338_70325607826620'

**Comment by Cycloone** [comment]
Fixed by query:
`delete from settings where name = "plugin_redmine_tags";`
