### ISSUE TITLE
Migrating from Redmine 3.3.0 (Ruby 2.3) (redmine_tags 3.2.2) to Redmine 4.1.7 (Ruby 2.6) (redmine_tags master branch) breaks plugin settings

### ISSUE THREAD

**Issue by danowar2k** [ixti/redmine_tags#234]
We're in the process of updating Redmine.

Before: Redmine 3.3.0 on Ruby 2.3 using redmine_tags 3.2.2
After: Redmine 4.1.7 on Ruby 2.6 using redmine_tags commit 2c0c66c73c36dfa53f6e6b2decf8828f49054d1d

What happens: Before the upgrade, the redmine_tags settings are stored this way:

```
--- !ruby/hash-with-ivars:ActionController::Parameters
elements:
  issues_sidebar: cloud
  issues_show_count: '1'
  issues_open_only: '1'
  issues_sort_by: name
  issues_sort_order: asc
ivars:
  :@permitted: false
```

After the update the plugin settings should (!) be stored this way:

```
--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
issues_sidebar: none
issues_sort_by: name
issues_sort_order: asc
```

When changing from Rails 4 to Rails 5, somewhere down the line ActiveRecord is updated so that this happens:

```
Caused by:
NoMethodError: undefined method `with_indifferent_access' for #<ActionController::Parameters:0x0ba909d8>
/app/tools/redmine/4.1.7/.appgems/ruby/2.6.0/gems/actionpack-5.2.6.3/lib/action_controller/metal/strong_parameters.rb:236:in `initialize'
/app/tools/redmine_tags/2c0c66c73c36dfa53f6e6b2decf8828f49054d1d/lib/redmine_tags.rb:3:in `new'
/app/tools/redmine_tags/2c0c66c73c36dfa53f6e6b2decf8828f49054d1d/lib/redmine_tags.rb:3:in `settings'
```

ActiveRecord wants to load the settings, expects a method called with_indifferent_access, but the old hash-with-ivars:ActionController::Parameters (if it even exists anymore), doesn't have one.

One solution is to add a migration step that loads the settings field avoiding ActiveRecord, transform it to a HashWithIndifferentAccess and store the settings again.

Like so:

```
class Testmigrate < ActiveRecord::Migration[4.2]
  def up
    new_settings = ActiveSupport::HashWithIndifferentAccess.new
    old_settings = Setting.plugin_redmine_tags
    old_settings.each do |key, value|
      new_settings[key] = value
    end
    Setting.send "plugin_redmine_tags=", new_settings
  end
end
```

This fixes the stored settings. I'll open a PR for this...

**Comment by danowar2k** [comment]
I know you would rather have the redmine_tags features present in core, but it doesn't seem there is much movement in that respect...
