### ISSUE TITLE
Plugin fails for non-admin accounts

### ISSUE THREAD

**Issue by eashman** [ixti/redmine_tags#62]
Here is an odd one:

As an admin, I can see issues lists w/o a problem.

For everyone else, when the redmine_tags plugin is enabled, it causes a SQL error.

This was after an upgrade to 2.3.2

Here's the error that comes up for those users:

```
Started GET "/projects/xxxxxxx/issues" for 10.17.12.150 at 2013-07-19 10:21:09 -0400
Processing by IssuesController#index as HTML
  Parameters: {"project_id"=>"xxxxxxxx"}
  Current user: xxxxxx (id=6)
  Rendered queries/_filters.html.erb (84.7ms)
  Rendered queries/_columns.html.erb (3.7ms)
  Rendered issues/_list.html.erb (93.6ms)
  Rendered plugins/redmine_graphs/app/views/hooks/redmine_graphs/_view_issues_sidebar_issues_bottom.html.erb (0.9ms)
  Rendered plugins/redmine_tags/app/views/issues/_tags_sidebar.html.erb (5.2ms)
  Rendered issues/_sidebar.html.erb (8.1ms)
  Rendered issues/index.html.erb within layouts/base (206.6ms)
Completed 500 Internal Server Error in 313ms

ActionView::Template::Error (Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')))) OR (projects.id IN (61,47,35,34,7,45,1,19,41,49,25,17,60,4,5,3,18,46,33,27,' at line 1: SELECT `issues`.`id` AS t0_r0, `issues`.`tracker_id` AS t0_r1, `issues`.`project_id` AS t0_r2, `issues`.`subject` AS t0_r3, `issues`.`description` AS t0_r4, `issues`.`due_date` AS t0_r5, `issues`.`category_id` AS t0_r6, `issues`.`status_id` AS t0_r7, `issues`.`assigned_to_id` AS t0_r8, `issues`.`priority_id` AS t0_r9, `issues`.`fixed_version_id` AS t0_r10, `issues`.`author_id` AS t0_r11, `issues`.`lock_version` AS t0_r12, `issues`.`created_on` AS t0_r13, `issues`.`updated_on` AS t0_r14, `issues`.`start_date` AS t0_r15, `issues`.`done_ratio` AS t0_r16, `issues`.`estimated_hours` AS t0_r17, `issues`.`parent_id` AS t0_r18, `issues`.`root_id` AS t0_r19, `issues`.`lft` AS t0_r20, `issues`.`rgt` AS t0_r21, `issues`.`is_private` AS t0_r22, `issues`.`position` AS t0_r23, `issues`.`closed_on` AS t0_r24, `projects`.`id` AS t1_r0, `projects`.`name` AS t1_r1, `projects`.`description` AS t1_r2, `projects`.`homepage` AS t1_r3, `projects`.`is_public` AS t1_r4, `projects`.`parent_id` AS t1_r5, `projects`.`created_on` AS t1_r6, `projects`.`updated_on` AS t1_r7, `projects`.`identifier` AS t1_r8, `projects`.`status` AS t1_r9, `projects`.`lft` AS t1_r10, `projects`.`rgt` AS t1_r11, `projects`.`inherit_members` AS t1_r12, `projects`.`dmsf_description` AS t1_r13, `issue_statuses`.`id` AS t2_r0, `issue_statuses`.`name` AS t2_r1, `issue_statuses`.`is_closed` AS t2_r2, `issue_statuses`.`is_default` AS t2_r3, `issue_statuses`.`position` AS t2_r4, `issue_statuses`.`default_done_ratio` AS t2_r5 FROM `issues` LEFT OUTER JOIN `projects` ON `projects`.`id` = `issues`.`project_id` LEFT OUTER JOIN `issue_statuses` ON `issue_statuses`.`id` = `issues`.`status_id` WHERE (((projects.status <> 9 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='issue_tracking')) AND ((projects.is_public = 1 AND ((issues.is_private = 0 OR issues.author_id = 6 OR issues.assigned_to_id IN (6,)))) OR (projects.id IN (61,47,35,34,7,45,1,19,41,49,25,17,60,4,5,3,18,46,33,27,32,29,2,14,36,26,13,22,23,24) AND ((issues.is_private = 0 OR issues.author_id = 6 OR issues.assigned_to_id IN (6,)))) OR (projects.id IN (43,44,40,45,10,49,11,37,39,38,12) AND ((issues.is_private = 0 OR issues.author_id = 6 OR issues.assigned_to_id IN (6,)))) OR projects.id IN (7,45,9,8,6) OR (projects.id IN (45) AND ((issues.is_private = 0 OR issues.author_id = 6 OR issues.assigned_to_id IN (6,)))) OR (projects.id IN (45) AND ((issues.is_private = 0 OR issues.author_id = 6 OR issues.assigned_to_id IN (6,))))))) AND (projects.id=60) AND (issue_statuses.is_closed = 0)):
    1: <% unless sidebar_tags.empty? -%>
    2:   <%= stylesheet_link_tag 'jquery.tagit.css', :plugin => 'redmine_tags' %>
    3:   <%= stylesheet_link_tag 'redmine_tags', :plugin => 'redmine_tags' %>
    4:   <h3><%= l(:tags) %></h3>
  lib/redmine/hook.rb:111:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/issues/_sidebar.html.erb:18:in `_app_views_issues__sidebar_html_erb__2750949893516397257_70362108906160'
  app/views/issues/index.html.erb:93:in `block in _app_views_issues_index_html_erb__549890581078395298_61647220'
  app/helpers/application_helper.rb:1158:in `content_for'
  app/views/issues/index.html.erb:92:in `_app_views_issues_index_html_erb__549890581078395298_61647220'
  app/controllers/issues_controller.rb:83:in `block (2 levels) in index'
  app/controllers/issues_controller.rb:82:in `index' 
```

**Comment by marius-balteanu** [comment]
In order to make a little clean up on this repository, we're closing all the issues older than 1 year.

Please check the latest version of the plugin and reopen this ticket if the issue/feature is still available.
