### ISSUE TITLE
another cross plugin bug

### ISSUE THREAD

**Issue by seqizz** [ixti/redmine_tags#84]
Looks like #14 ,
```
Started GET "/my/page" for 85.105.100.85 at 2014-02-04 15:30:19 +0200
Processing by MyController#page as HTML
  Current user: xxxxx (id=4)
  Rendered plugins/redmine_my_page_queries/app/views/my/_query_block.html.erb (556.6ms)
  Rendered plugins/redmine_my_page_queries/app/views/my/page.html.erb within layouts/base (595.3ms)
Completed 500 Internal Server Error in 607.7ms

ActionView::Template::Error (undefined method `render_tag_link' for #<#<Class:0x000000046835e0>:0x007f1b09aa2c58>):
    34:             <% previous_group = group %>
    35:           <% end %>
    36:           <tr id="issue-<%= issue.id %>" class="hascontextmenu <%= cycle('odd', 'even') %> <%= issue.css_classes %> <%= level > 0 ? "idnt idnt-#{level}" : nil %>">
    37:             <td class="checkbox hide-when-print"><%= check_box_tag("ids[]", issue.id, false, :id => nil) %></td>
    38:             <%= raw query.inline_columns.map {|column| "<td class=\"#{column.css_classes}\">#{column_content(column, issue)}</td>"}.join %>
    39:           </tr>
    40:           <% query.block_columns.each do |column|
  app/helpers/issues_helper.rb:29:in `block in issue_list'
  app/helpers/issues_helper.rb:25:in `each'
  app/helpers/issues_helper.rb:25:in `issue_list'
```

using plugins redmine_tags and redmine_my_page_queries . Please inform if I'm opening this bug to wrong plugin.

**Comment by marius-balteanu** [comment]
In order to make a little clean up on this repository, we're closing all the issues older than 1 year.

Please check the latest version of the plugin and reopen this ticket if the issue/feature is still available.
